### ISSUE TITLE
Split

### ISSUE THREAD

**Issue by spinualexandru** [salcosta/sn-node#2]
Making Request to: https://bioradtest.service-now.com/login.do
/home/okei/dev/biodash/node_modules/sn-node/sn-node.js:86
                var ck = result.split("var g_ck = '")[1].split('\'')[0];
                                                        ^

TypeError: Cannot read property 'split' of undefined
    at ServiceNow.self.set_token (/home/okei/dev/biodash/node_modules/sn-node/sn-node.js:86:43)
    at ServiceNow.self.check_state (/home/okei/dev/biodash/node_modules/sn-node/sn-node.js:176:32)
    at Request._callback (/home/okei/dev/biodash/node_modules/sn-node/sn-node.js:165:24)
    at Request.self.callback (/home/okei/dev/biodash/node_modules/sn-node/node_modules/request/request.js:129:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/okei/dev/biodash/node_modules/sn-node/node_modules/request/request.js:873:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/okei/dev/biodash/node_modules/sn-node/node_modules/request/request.js:824:12)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by rnreekez** [comment]
Might have figured this out already but I ended up needing to use the .login method first to get the token that is used to authenticate

**Comment by spinualexandru** [comment]
@rnreekez - Any idea how to fix this? I did not fix it yet. :(

**Comment by spinualexandru** [comment]
Changed: var ck = result.split("var g_ck = '")[1].split('\'')[0];
To: var ck = result.split("var g_ck = '")[0].split('\'')[0];
-> Worked ( if your servicenow instance is newer than Calgary. )

**Comment by salcosta** [comment]
I have never been able to reproduce this.  As @rnreekez said it was probably missing, I have verified this works up to Helsinki.
